# Generated by Django 5.2 on 2025-09-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_userprofile_fname_userprofile_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
